### ISSUE TITLE
grub-mkfont command not found

### ISSUE THREAD

**Issue by keeferrourke** [Dragon8oy/argon-grub-theme#1]
On Fedora 33, the grub commands used in install.sh don't work. Instead, the script should look for the following grub2 commands:

 - `grub2-mkfont`
 - `grub2-mkconfig`

**Comment by stuarthayhurst** [comment]
Thanks, I'll look into this :)

**Comment by stuarthayhurst** [comment]
Can you test merge request #2 please? This should fix your issue :)

**Comment by stuarthayhurst** [comment]
Since this doesn't break anything, I'm going to go ahead and merge the pr. When you get a chance, could you test the fix on the master branch please?
Thanks :)

**Comment by keeferrourke** [comment]
Can confirm that #2 fixed the grub font issue!
