### ISSUE TITLE
grub2 error: png: color type not supported

### ISSUE THREAD

**Issue by puzzle9** [Dragon8oy/argon-grub-theme#10]
install 
`sudo ./install.sh --install --resolution 2k --background Grey`

restart grub2 error:
`grub2 error: png: color type not supported`

![IMG_20220722_212519](https://user-images.githubusercontent.com/13518196/180449064-691b0351-1cb2-4661-901a-6452457c8825.jpg)

**Comment by stuarthayhurst** [comment]
Hm, it appears that wallpaper uses a weird colour profile, I'll fix the build scripts and update the wallpaper

**Comment by stuarthayhurst** [comment]
Should be fixed on `master`

**Comment by puzzle9** [comment]
It seems that not many people use this picture
