### ISSUE TITLE
Themes do not get applied after a seemingly sucessful install (Nobara OS) 

### ISSUE THREAD

**Issue by RuShiiiiii** [Dragon8oy/argon-grub-theme#11]
I don't know what info would be helpful, this is my very first attempt to theme grub and this is my very first issue on GitHub.

I ran this line in the terminal to install: `sudo ./install.sh --install --resolution 1920x1080 --background Crystals` and received the prompt from the script signaling I was using some default settings etc. Pressed enter, rebooted, but grub was unchanged.

I saw that a folder in usr/share/.../grub got created and the file etc/default/grub modified.
However I did not find anything in /boot/grub2/themes as I expected. Is that expected from your end?

As stated bellow, I don't know anything about what's supposed to happen, I just spent a few minutes looking around to try to troubleshoot.

Btw, lastly, I think it'd be good to have an uninstall command in your script.
--> it could backup the modified files at install and restore them at uninstall + remove what was added.

Anyway, I don't want to waste your time, so you can just close this is none of what I said made sense :sweat_smile:

**Comment by stuarthayhurst** [comment]
> Btw, lastly, I think it'd be good to have an uninstall command in your script.
> --> it could backup the modified files at install and restore them at uninstall + remove what was added.

`sudo ./install.sh --uninstall` should take care of that :)

As for the main issue, try `sudo ./install.sh --install --resolution 1920x1080 --background Crystals --boot`
`--boot` tells the theme to install itself into `/boot/grub/themes` or `/boot/grub2/themes`, whichever it detects

**Comment by RuShiiiiii** [comment]
> sudo ./install.sh --uninstall should take care of that :)

I feel dumb, I don't know how I missed that.


About the issue, I (or you, Idk who should do that) should close it.

The os I'm using is a fork of fedora. I had seen I had to do `sudo grub2-mkconfig -o /boot/grub2/grub.cfg` to update grub, but didn't see I had to comment out GRUB_TERMINAL_OUTPUT="console" in etc/default/grub.
--> it is finally working as intended.

Now I'm faced with the next issue: how to setup grub to hide the recovery and other entries?
(If you add the 2 entries I have for my current os, here is what I have in my menu)
```
[rushi@nitro-an515-54 ~]$ sudo awk -F\' '/menuentry / {print $2}' /boot/grub2/grub.cfg 
[sudo] password for rushi: 
Pop!_OS 22.04 LTS (22.04) (on /dev/nvme1n1p3)
Pop!_OS 22.04 LTS (22.04) (on /dev/nvme1n1p3)
Pop!_OS 22.04 LTS (22.04) (on /dev/nvme1n1p3)
Pop!_OS 22.04 LTS (22.04) (on /dev/nvme1n1p3)
Pop!_OS 22.04 LTS (22.04) (on /dev/nvme1n1p3)
Pop!_OS 22.04 LTS (22.04) (on /dev/nvme1n1p3)
Pop!_OS 22.04 LTS (22.04) (on /dev/nvme1n1p3)
Pop!_OS 22.04 LTS (22.04) (on /dev/nvme1n1p3)
Pop!_OS 22.04 LTS (22.04) (on /dev/nvme1n1p3)
Pop!_OS 22.04 LTS (22.04) (on /dev/nvme1n1p3)
Pop!_OS 22.04 LTS (22.04) (on /dev/nvme1n1p3)
Pop!_OS 22.04 LTS (22.04) (on /dev/nvme1n1p3)
UEFI Firmware Settings
```
Maybe another option in your wonderful theme could do the trick? :wink:
Or is the solution another trivial thing I don't know?...

**Comment by stuarthayhurst** [comment]
The entries shown aren't the theme's responsibility, that's down to GRUB config. You may be able to get somewhere using [GRUB customizer](https://itsfoss.com/install-grub-customizer-ubuntu/), best of luck :)
