### ISSUE TITLE
Preview error 'GRUB platform directory "/usr/lib/grub/x86_64-efi" not found'

### ISSUE THREAD

**Issue by keeferrourke** [Dragon8oy/argon-grub-theme#3]
I've installed `grub2-theme-preview` according to the docs, however running `install.sh -p -b Night` fails with an error:

```
INFO: Could not read external GRUB config file, falling back to internal example config
ERROR: [Errno 2] GRUB platform directory "/usr/lib/grub/x86_64-efi" not found
```

This is on Fedora 33 Workstation running on a Dell XPS 13 2-in-1 7390.

**Comment by stuarthayhurst** [comment]
Thanks again, I'll make a VM and take a look

**Comment by stuarthayhurst** [comment]
I can't seem to reproduce this issue on Debian or in my VM...
I don't think this is an issue with my code, but rather grub2-theme-preview, or a missing file from grub. On my Debian Sid installation, `grub-efi-amd64-bin` provides `/usr/lib/grub/x86_64-efi`. Could it be that you're missing the package that provides this, if it's required on your install?
On the fresh Fedora 33 installation I made, grub2-theme-preview runs fine, with no error, but `/usr/lib/grub/x86_64-efi` also isn't there, which leads me to believe that this is a problem with grub2-theme-preview itself.

**Comment by keeferrourke** [comment]
Your comments helped me pin down the issue, thanks! On Fedora `grub2-efi-x64-modules` provides that directory. After installing that package, the preview works as expected now! :smile:

**Comment by stuarthayhurst** [comment]
Glad it's working now! Do you think it's worth making a bug report / pull request for grun2-theme-preview with this info to help others?

**Comment by keeferrourke** [comment]
Might not be a bad idea. That repo has pretty sparse installation instructions. Took me a bit to figure out how to get it working!
