### ISSUE TITLE
[Feature request] Different icon themes (white)

### ISSUE THREAD

**Issue by jacksongoode** [Dragon8oy/argon-grub-theme#4]
It would be great to have colorless icons as a parameter as well!

**Comment by stuarthayhurst** [comment]
Sorry, I don't have a lot of interest in colourless icons, and it'd be rather time consuming to recreate all the icons as colourless. I'm not going to do this myself, but I can handle the scripting if somebody else handles the icons.

**Comment by jacksongoode** [comment]
Yeah, of course. Would using icons from [this project](https://github.com/vinceliuice/grub2-themes) potentially work? Or is your main concern the svgs? In which case would pulling from https://materialdesignicons.com/ work - if so I can make a PR with the svgs.

Edit: Wow! Just now realized you're the author of the icon pack! Great work!

**Comment by stuarthayhurst** [comment]
I'm not the only author of the icons at grub2-themes, I contributed enough that the main author let me reuse them here, and I've added more here since. I don't have any concerns about the icons as long as they can be properly licensed, so feel free to submit a PR if that's the case, and I'll handle the scripting and multithreading.

**Comment by stuarthayhurst** [comment]
Actually, it shouldn't be too much work to do white versions of the existing icons. I'm currently updating and tweaking most of the icons in the theme, afterwards I'll start work on creating colourless versions.

**Comment by stuarthayhurst** [comment]
Support for colourless icons is in the build system, I'll start work on the new icons next.

**Comment by stuarthayhurst** [comment]
New icons are in the master branch :)
If you want to modify any, feel free to submit a PR.
