### ISSUE TITLE
Not Able to Install Theme

### ISSUE THREAD

**Issue by Ronald545** [Dragon8oy/argon-grub-theme#8]
Hi have been using your theme for quite some time and i love it.
I decided to install it for my new installation of Endeavour OS
however, this error happened when i tried to install the theme, other commands also don't work
![image](https://user-images.githubusercontent.com/63299413/141254137-623c5ae0-1879-41c2-921f-463b2507ffcc.png)

hopefully you can get this fixed :), thanks so much for your effort

**Comment by stuarthayhurst** [comment]
Thanks, I'll look into this later today :)

**Comment by stuarthayhurst** [comment]
All done, thanks :)
